name = "wehelp"
account_id = "f95aa84daa9d32075ef113a4382fdfc2"
workers_dev = true
main = ".output/index.js"

[site]
bucket = ".output/public"

[build]
command = "true"
upload.format = "service-worker"

# [secrets]
# BASE_ID
# API_KEY
